Ncnews 10 get articles queries
michaelafm/be-nc-news pull request #9
Opened 2022-11-17 16:04 UTC by michaelafm

2022-11-17 16:12 UTC, callumu21 requested changes
Great start! Just need to consider two different test cases and how you can differentiate between them in your model

2022-11-17 16:12 UTC, callumu21 commented on __tests__/app.test.js
> +  test("GET: 200 - returns empty array when given non-existent topic", () => {
You will need to consider two different cases here:

- Happy path: The topic is in the database but has no associated articles
- Sad path: The topic is invalid and not in the database

2022-11-18 09:47 UTC, michaelafm commented on __tests__/app.test.js
> +  test("GET: 200 - returns empty array when given non-existent topic", () => {
Two distinct tests added for topic with no associated articles and invalid topic

2022-11-18 09:53 UTC, Geo-Beard commented
Changes implemented - looks good! Feel free to merge and move on :)

2022-11-18 09:54 UTC, merged